### ISSUE TITLE
Looking forward to the official release

### ISSUE THREAD

**Issue by qiaodan-cuhk** [dematsunaga/alberdice#1]
Dear author,

I found this official link from your camera ready version paper of NIPS'23. The idea of alternative BR is amazing for offline MARL. I'm trying to make some future attempt in this line based on your pioneer work. I'm quietly interested in the detailed implementation about this project. Would u like to consider updating GitHub code? Many thanks for your works! 🤗🤗

Best

**Comment by dematsunaga** [comment]
Thank you for your patience. The code is released now. Please let us know if you have any further questions.

**Comment by qiaodan-cuhk** [comment]
Thanks a million for your reply :)
